spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL}
    password: ${PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  datasource:
    url: 'jdbc:mysql://localhost:3306/lapshop'
    username: root
    password: pass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 240628607955-h8lnaata5n82q96lf2b1hr8hlm8ccaso.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile
server:
  error:
    whitelabel:
      enabled: false
    include-exception: true
    include-stacktrace: always
upload:
  path: 'C:/Users/user/Desktop/LaptopShop/src/main/resources/imgs'




